import { PCFSoftShadowMap, PCFShadowMap } from "three";

export const DEVICE_PRESETS = {
  highEnd: {
    precision: "highp",
    pixelRatio: () => Math.min(window.devicePixelRatio, 2),
    shadowMapEnabled: true,
    shadowMapType: PCFSoftShadowMap,
    shadowMapSize: 2048,
    contactShadow: true,
    spotLightsOn: true,
    floor: true,
    touchMoveListener: true,
    renderTargetRes: 2048,
    hdrIntensity: 0.45,
  },
  lowEnd: {
    precision: "mediump",
    pixelRatio: () => 1,
    shadowMapEnabled: false,
    shadowMapType: PCFShadowMap,
    shadowMapSize: 256,
    contactShadow: true,
    spotLightsOn: false,
    floor: true,
    touchMoveListener: true,
    renderTargetRes: 128,
    hdrIntensity: 0.4,
    targetFPS: 30,
  },
  mobile: {
    precision: "mediump",
    pixelRatio: () => Math.min(window.devicePixelRatio, 2),
    shadowMapEnabled: false,
    shadowMapType: PCFShadowMap,
    shadowMapSize: 256,
    contactShadow: false,
    spotLightsOn: false,
    floor: false,
    touchMoveListener: false,
    renderTargetRes: 1024,
    hdrIntensity: 0.4,
  },
};
